site_name: Contas Alfa

repo_url: https://github.com/csalpha-team/csalpha
site_url: https://csalpha-team.github.io/csalpha/

theme:
  name: material
  features:
    - header.autohide
    - navigation.sections
    - navigation.top
    - toc.integrate
    - navigation.tabs

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/csalpha-team/csalpha

nav:
  - Home: index.md
  - Documentação: documentacao.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            rendering_opt: "value"       
          setup_commands:
            - import sys
            - sys.path.insert(0, "csalpha")
            - print(sys.path)

