name: CSAlpha Push Pull-Request Checker

on:
  push:
  pull_request:

jobs:
  build-n-publish:
    name: Build and Test CSAlpha
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 'pypy-3.7']  # Specify Python versions here

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements_dev.txt
          pip install setuptools wheel twine tox pytest

      - name: Install pypa/build
        run: |
          python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/
          
      - name: Running Tests
        run: |
          tox